// Using VITE_PUBLIC_DATA_KEY from .env
const API_KEY = import.meta.env.VITE_PUBLIC_DATA_KEY;

export interface WeatherData {
  tmp: string; // temperature
  sky: string; // sky condition
  pop: string; // probability of precipitation
  pty: string; // precipitation type
  reh: string; // humidity
}

export const WeatherService = {
  // Ultra Short Term Forecast (Cho-dan-gi)
  // Ultra Short Term Forecast (Cho-dan-gi)
  async getRealtimeWeather(lat: number, lng: number): Promise<WeatherData | null> {
    
    // NAS Caching Strategy:
    // Instead of calculating Grid(NX,NY) and calling KMA API efficiently (which requires proxy + key),
    // we fetch the pre-cached 'weather.json' generated by 'scripts/fetch_data.js'.
    // Note: lat/lng arguments are ignored here because the script is configured for the specific farm location.
    
    try {
      // Add timestamp to prevent browser caching of static file
      const url = `/data/kma/weather.json?t=${new Date().getTime()}`;
      
      const response = await fetch(url);
      if (!response.ok) throw new Error('NAS Weather Cache not found');

      const data = await response.json();
      
      if (data.error) {
          console.warn('Weather data in cache indicates error');
          return null;
      }

      return {
        tmp: data.tmp,
        sky: data.sky,
        pop: data.pop,
        pty: data.pty, // 0:None, 1:Rain, 2:Sleet, 3:Snow, 4:Shower
        reh: data.reh,
      };

    } catch (error) {
      console.warn('Weather fetch from NAS failed:', error);
      return null;
    }
  },
};

// --- KMA Coordinate Conversion Logic (Lambert Conformal Conic) ---
// RE=6371.00877, GRID=5.0, SLAT1=30.0, SLAT2=60.0, OLON=126.0, OLAT=38.0, XO=43, YO=136
function dfs_xy_conv(code: string, v1: number, v2: number) {
    const RE = 6371.00877; // Earth radius (km)
    const GRID = 5.0; // Grid spacing (km)
    const SLAT1 = 30.0 * Math.PI / 180.0;
    const SLAT2 = 60.0 * Math.PI / 180.0;
    const OLON = 126.0 * Math.PI / 180.0;
    const OLAT = 38.0 * Math.PI / 180.0;
    const XO = 43;
    const YO = 136;

    const DEGRAD = Math.PI / 180.0;
    const RADDEG = 180.0 / Math.PI;

    const re = RE / GRID;
    const slat1 = SLAT1;
    const slat2 = SLAT2;
    const olon = OLON;
    const olat = OLAT;

    let sn = Math.tan(Math.PI * 0.25 + slat2 * 0.5) / Math.tan(Math.PI * 0.25 + slat1 * 0.5);
    sn = Math.log(Math.cos(slat1) / Math.cos(slat2)) / Math.log(sn);
    let sf = Math.tan(Math.PI * 0.25 + slat1 * 0.5);
    sf = Math.pow(sf, sn) * Math.cos(slat1) / sn;
    let ro = Math.tan(Math.PI * 0.25 + olat * 0.5);
    ro = re * sf / Math.pow(ro, sn);

    const rs: any = {};
    if (code === "toXY") {
        rs['lat'] = v1;
        rs['lng'] = v2;
        let ra = Math.tan(Math.PI * 0.25 + (v1) * DEGRAD * 0.5);
        ra = re * sf / Math.pow(ra, sn);
        let theta = v2 * DEGRAD - olon;
        if (theta > Math.PI) theta -= 2.0 * Math.PI;
        if (theta < -Math.PI) theta += 2.0 * Math.PI;
        theta *= sn;
        rs['x'] = Math.floor(ra * Math.sin(theta) + XO + 0.5);
        rs['y'] = Math.floor(ro - ra * Math.cos(theta) + YO + 0.5);
    }
    return rs;
}
